---

- name: installing glusterd dependency
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ glusterfs_server_dependencies }}"

- name: adding glusterd repository
  apt_repository:
    repo: ppa:gluster/glusterfs-4.0
    state: present

- name: installing glusterd
  apt:
    update_cache: yes
    name: glusterfs-server
    state: latest

- name: enabling the right kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ glusterfs_server_modules }}"

- name: enabling the right kernel modules at boot
  lineinfile:
    state: present
    path: /etc/modules-load.d/glusterd.conf
    line: "{{ item }}"
    create: yes
  with_items: "{{ glusterfs_server_modules }}"

- name: enabling systemd-modules-load service
  systemd:
    name: systemd-modules-load
    enabled: yes
    state: started

- name: enabling and restarting glusterd
  systemd:
    name: glusterd
    enabled: yes
    daemon_reload: yes
    state: restarted

