---

- name: enabling the right kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ glusterfs_client_modules }}"

- name: enabling the right kernel modules at boot
  lineinfile:
    state: present
    path: /etc/modules-load.d/glusterd.conf
    line: "{{ item }}"
    create: yes
  with_items: "{{ glusterfs_client_modules }}"

- name: enabling systemd-modules-load service
  systemd:
    name: systemd-modules-load
    enabled: yes
    state: started

- name: installing glusterfs-client on all nodes
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ glusterfs_client_dependencies }}"
